databases:
  - name: mysite
    databaseName: mysite_ccz7
    user: mysite

services:
  - type: web
    name: wilhelm-realtime-searchbox
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite_ccz7
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false